# Generated by Django 5.1.5 on 2025-01-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="match", name="score",),
        migrations.AddField(
            model_name="match",
            name="set_scores",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
