# Generated by Django 5.1.5 on 2025-01-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0002_remove_match_score_match_set_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match", name="set_scores", field=models.JSONField(default=list),
        ),
    ]
