# Generated by Django 5.1.5 on 2025-01-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0003_alter_match_set_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="usta_rating",
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
