# Generated by Django 5.1.5 on 2025-01-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0004_player_usta_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="usta_rating",
            field=models.FloatField(default=3.0),
        ),
    ]
