# Generated by Django 5.1.5 on 2025-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0005_alter_player_usta_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match", name="date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="match", name="set_scores", field=models.JSONField(),
        ),
    ]
