# Generated by Django 5.1.5 on 2025-02-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_player_neighborhood_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='neighborhood',
            field=models.CharField(choices=[('Brickell', 'Brickell'), ('Coconut Grove', 'Coconut Grove'), ('Coral Gables', 'Coral Gables'), ('Design District', 'Design District'), ('Doral', 'Doral'), ('Downtown', 'Downtown'), ('Edgewater', 'Edgewater'), ('Fort Lauderdale', 'Fort Lauderdale'), ('Kendall', 'Kendall'), ('Key Biscayne', 'Key Biscayne'), ('Little Havana', 'Little Havana'), ('Miami Beach', 'Miami Beach'), ('Midtown', 'Midtown'), ('Morningside', 'Morningside'), ('Palmetto Bay', 'Palmetto Bay'), ('Pinecrest', 'Pinecrest'), ('South Miami', 'South Miami'), ('Weston', 'Weston'), ('Wynwood', 'Wynwood')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='ELOHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='rankings.player')),
            ],
        ),
    ]
