# Generated by Django 5.1.5 on 2025-02-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0008_alter_player_neighborhood_elohistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elohistory", name="date", field=models.DateTimeField(),
        ),
    ]
