# Generated by Django 5.1.5 on 2025-02-05 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0009_alter_elohistory_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
