# Generated by Django 5.1.5 on 2025-02-05 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0011_match_submitted_at_match_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="elohistory",
            name="match",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elo_history",
                to="rankings.match",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elohistory",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
