# Generated by Django 5.1.5 on 2025-02-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0012_elohistory_match_elohistory_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
