# Generated by Django 5.1.5 on 2025-02-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0013_player_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_approved',
        ),
    ]
