# Generated by Django 5.1.5 on 2025-02-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_player_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
