# Generated by Django 5.1.5 on 2025-02-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_match_loser_elo_after_match_loser_elo_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elohistory',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
