# Generated by Django 5.1.5 on 2025-02-21 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0018_player_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo_rating_doubles',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='neighborhood',
            field=models.CharField(choices=[('Brickell', 'Brickell'), ('Coconut Grove', 'Coconut Grove'), ('Coral Gables', 'Coral Gables'), ('Design District', 'Design District'), ('Doral', 'Doral'), ('Downtown', 'Downtown'), ('Edgewater', 'Edgewater'), ('Fort Lauderdale', 'Fort Lauderdale'), ('Kendall', 'Kendall'), ('Key Biscayne', 'Key Biscayne'), ('Little Havana', 'Little Havana'), ('Miami Beach', 'Miami Beach'), ('Midtown', 'Midtown'), ('Morningside', 'Morningside'), ('Palmetto Bay', 'Palmetto Bay'), ('Pinecrest', 'Pinecrest'), ('Shenandoah', 'Shenandoah'), ('South Miami', 'South Miami'), ('Weston', 'Weston'), ('Wynwood', 'Wynwood')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='MatchDoubles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner1_elo_before', models.IntegerField(blank=True, null=True)),
                ('winner2_elo_before', models.IntegerField(blank=True, null=True)),
                ('loser1_elo_before', models.IntegerField(blank=True, null=True)),
                ('loser2_elo_before', models.IntegerField(blank=True, null=True)),
                ('winner1_elo_after', models.IntegerField(blank=True, null=True)),
                ('winner2_elo_after', models.IntegerField(blank=True, null=True)),
                ('loser1_elo_after', models.IntegerField(blank=True, null=True)),
                ('loser2_elo_after', models.IntegerField(blank=True, null=True)),
                ('set_scores', models.JSONField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('loser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_doubles_matches1', to='rankings.player')),
                ('loser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_doubles_matches2', to='rankings.player')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_doubles_matches', to=settings.AUTH_USER_MODEL)),
                ('winner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_doubles_matches1', to='rankings.player')),
                ('winner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_doubles_matches2', to='rankings.player')),
            ],
        ),
        migrations.CreateModel(
            name='ELOHistoryDoubles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating_doubles', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history_doubles', to='rankings.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history_doubles', to='rankings.matchdoubles')),
            ],
        ),
    ]
