# Generated by Django 5.1.5 on 2025-03-14 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rankings",
            "0019_player_elo_rating_doubles_alter_player_neighborhood_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="elohistorydoubles",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
